### ISSUE TITLE
Move provider to upstream terraform-providers

### ISSUE THREAD

**Issue by dghubble** [poseidon/terraform-provider-ct#21]
Maintaining `terraform-provider-ct` in terraform-providers would allow it to be pulled via `terraform init`. I've mentioned being willing to champion/maintain this. Needs someone from Hasicorp with the ability to create a repo in that org.

rel:

* https://github.com/coreos/terraform-provider-ct/issues/2#issuecomment-356352177
* https://github.com/coreos/terraform-provider-ct/issues/20

**Comment by dghubble** [comment]
I'm work with Hasicorp on getting `terraform-provider-matchbox` in the official providers list. That's the guinea pig. Depending on how that goes, this will be next.

**Comment by mishak87** [comment]
@dghubble Any update on this?

**Comment by dghubble** [comment]
Well, Hashicorp couldn't take the matchbox plugin. Maybe not a good guinea pig. Unlike a cloud provider API, you deploy the Matchbox service within your org to get an API for Terraform to speak to. Its not compatible with how Hashicorp tests / validates remote providers.

I'll try submitting `terraform-provider-ct`. It has no remote API or server and just transforms local files, so hopefully they'll be ok with it.

**Comment by nikolay** [comment]
@dghubble Any update?

**Comment by dghubble** [comment]
I filled out the application 11 days ago. I have not yet received a response.
