### ISSUE TITLE
Terraform 0.12.0 compatible release

### ISSUE THREAD

**Issue by invidian** [poseidon/terraform-provider-ct#44]
Terraform 0.12.0 has been released yesterday and if users wants to migrate, currently last release version is not compatible with it. Attempt to upgrade results in:
```
-----------------------------------------------------------------------------

Error: failed to load provider "ct": Incompatible API version with plugin. Plugin version: 4, Client versions: [5]
```

Could we have a new release, ideally with https://github.com/poseidon/terraform-provider-ct/pull/43 included?

**Comment by dghubble** [comment]
Closed by https://github.com/poseidon/terraform-provider-ct/pull/48
