### ISSUE TITLE
Support for Terraform 0.12?

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [poseidon/terraform-provider-ct#50]
We wanted to use this plugin, but are moving to Terraform 0.12.

According to these docs, changes may need to be made to the plugin to support this:

https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html

Are there any plans to support 0.12?

Another possibility would be using the Matchbox or Ignition plugins.

**Comment by dghubble** [comment]
Please read https://github.com/poseidon/terraform-provider-ct/blob/master/CHANGES.md, its already done.
