### ISSUE TITLE
Plans for updating to latest ignition

### ISSUE THREAD

**Issue by dragan** [poseidon/terraform-provider-ct#54]
👋 @dghubble

I recently [added proxy support](https://github.com/coreos/ignition/pull/733) and [backport](https://github.com/coreos/ignition/pull/770) to ignition and it was released as part of the experimental config in [0.32.0](https://github.com/coreos/ignition/tree/v0.32.0). I use this plugin in our terraform and I was wondering:

1. Are you currently working on updating to latest?
2. If not, would you be interested in accepting a contribution?
3. If so, what are the steps to get this updated?

Thanks in advance!

**Comment by dghubble** [comment]
For context, the `container-linux-config-transpiler` is what's relevant for `terraform-provider-ct` Container Linux Config validation. The Ignition library must align with that, it does not make sense to bump it independently.

In `terraform-provider-ct` v0.4.0, Container Linux Config are rendered as Ignition v2.2.0 and Fedora CoreOS Configs support up to v3.0.0. When spec v2.3.0 is released, this provider will update to align with that verison. See https://github.com/coreos/container-linux-config-transpiler/pull/165. Your contribution was not added until the v2.4.0 and v3.1.0 spec's. Those bumps will come in future when new releases of clct and fcct transpiler libraries are available.

**Comment by dragan** [comment]
I see, thanks for the context. I will work around for now as I only need the proxy section when retrieving replacement configs during boot up at the moment, which means my initial config is really small. As a work around, I can just maintain the config in json format with templates.

I'm going to close this for now and I will keep an eye out for the updates. Thanks!
