### ISSUE TITLE
Naming needs some tweaking

### ISSUE THREAD

**Issue by crawford** [poseidon/terraform-provider-ct#7]
"ct" refers to the container-linux-config-transpiler - a tool for transpiling from Container Linux Configs to Ignition Configs. I think it might make more sense to not tie this provider to ct explicitly, but instead just consume the ct library. Maybe this would be called terraform-provider-clc instead. There are also a few references in the README that should be updated to refer to the ingested configuration as Container Linux Configs.

**Comment by crawford** [comment]
I think this should be a blocker for https://github.com/coreos/terraform-provider-ct/issues/2.

**Comment by dghubble** [comment]
`terraform-provider-container-linux` or `terraform-provider-container-linux-config`

**Comment by dghubble** [comment]
Close this last issue and track issues in coreos/bugs?

**Comment by dghubble** [comment]
The "exported" resource should probably be called "config" so we probably want terraform-provider-container-linux so it reads `resource "container_linux_config" { ... }` in terraform definitions

**Comment by dghubble** [comment]
A tthis point, just going to stick with it and maybe re-evaluate once Fedora CoreOS is broadly used.
